name: CI - Reto Datepicker

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      # Instala Google Chrome estable en el runner
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      # Ejecuta las pruebas en modo headless
      - name: Build & Test (mvn verify - headless)
        run: |
          mvn -B -e \
            -Dwebdriver.driver=chrome \
            -Dserenity.use.headless.mode=true \
            -Dchrome.switches="--headless=new --no-sandbox --disable-dev-shm-usage --window-size=1920,1080" \
            clean verify

      # Publica el reporte de Serenity como artefacto descargable
      - name: Upload Serenity Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: serenity-report
          path: target/site/serenity/**

      # Publica los surefire reports por si hay fallas
      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/**
